language: node_js
node_js:
  - v4
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; npm --version; fi
script: "./node_modules/karma/bin/karma start test/karma.conf.js --browsers Firefox --single-run --no-auto-watch --capture-timeout 60000"
